// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sampark.Data;

#nullable disable

namespace Sampark.Migrations
{
    [DbContext(typeof(SamparkDbContext))]
    partial class SamparkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sampark.Models.Entity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityId"));

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("created_at")
                        .HasColumnType("text");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<int?>("division_geo_level_id")
                        .HasColumnType("integer");

                    b.Property<int?>("division_id")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<int>("is_active")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int?>("parent_entity_id")
                        .HasColumnType("integer");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("updated_at")
                        .HasColumnType("text");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.Property<string>("uuid")
                        .HasColumnType("text");

                    b.HasKey("EntityId");

                    b.HasIndex("parent_entity_id");

                    b.ToTable("entities");
                });

            modelBuilder.Entity("Sampark.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BapsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PrimaryPersonId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Sampark.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProjectUuCode")
                        .HasColumnType("uuid")
                        .HasColumnName("project_uucode");

                    b.Property<string>("ReminderFrequency")
                        .HasColumnType("text");

                    b.Property<string>("ReminderFrequencyConfig")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("project");
                });

            modelBuilder.Entity("Sampark.Models.ProjectFamily", b =>
                {
                    b.Property<int>("ProjectFamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("project_family_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectFamilyId"));

                    b.Property<int?>("AssignedKaryakarPairId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_karyakar_pair_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<int?>("MandalId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryPersonId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectFamilyUuCode")
                        .HasColumnType("uuid")
                        .HasColumnName("project_family_uucode");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("ProjectFamilyId");

                    b.HasIndex("AssignedKaryakarPairId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_family");
                });

            modelBuilder.Entity("Sampark.Models.ProjectKaryakar", b =>
                {
                    b.Property<int>("ProjectKaryakarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("project_karyakar_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectKaryakarId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("KaryakarPersonId")
                        .HasColumnType("integer");

                    b.Property<int?>("MandalId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ProjectKaryakarUuCode")
                        .HasColumnType("uuid")
                        .HasColumnName("project_karyakar_uucode");

                    b.HasKey("ProjectKaryakarId");

                    b.HasIndex("KaryakarPersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_karyakar");
                });

            modelBuilder.Entity("Sampark.Models.ProjectKaryakarPair", b =>
                {
                    b.Property<int>("KaryakarPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("karyakar_pair_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KaryakarPairId"));

                    b.Property<Guid>("KaryakarPairUuCode")
                        .HasColumnType("uuid")
                        .HasColumnName("karyakar_pair_uucode");

                    b.Property<string>("PairType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrimaryKaryakarPersonId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("SecondaryKaryakarPersonId")
                        .HasColumnType("integer");

                    b.HasKey("KaryakarPairId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_karyakar_pair");
                });

            modelBuilder.Entity("Sampark.Models.Entity", b =>
                {
                    b.HasOne("Sampark.Models.Entity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("parent_entity_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Sampark.Models.ProjectFamily", b =>
                {
                    b.HasOne("Sampark.Models.ProjectKaryakarPair", "AssignedKaryakarPair")
                        .WithMany("AssignedFamilies")
                        .HasForeignKey("AssignedKaryakarPairId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sampark.Models.Project", "Project")
                        .WithMany("Families")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedKaryakarPair");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sampark.Models.ProjectKaryakar", b =>
                {
                    b.HasOne("Sampark.Models.Person", "KaryakarPerson")
                        .WithMany()
                        .HasForeignKey("KaryakarPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sampark.Models.Project", "Project")
                        .WithMany("Karyakars")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KaryakarPerson");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sampark.Models.ProjectKaryakarPair", b =>
                {
                    b.HasOne("Sampark.Models.Project", "Project")
                        .WithMany("KaryakarPairs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Sampark.Models.Entity", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Sampark.Models.Project", b =>
                {
                    b.Navigation("Families");

                    b.Navigation("KaryakarPairs");

                    b.Navigation("Karyakars");
                });

            modelBuilder.Entity("Sampark.Models.ProjectKaryakarPair", b =>
                {
                    b.Navigation("AssignedFamilies");
                });
#pragma warning restore 612, 618
        }
    }
}
